org: carmoconsulting
app: serverless-guard
service: serverless-guard

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: index.api
    events:
      - httpApi: "*"

plugins:
  - serverless-esbuild
  - serverless-offline